### ISSUE TITLE
[请教]关于实现hexo主题

### ISSUE THREAD

**Issue by QAQMiao** [levonlin/Tinnypp#2]
你好，我今天刚刚学习了通过hexo搭建自己的博客，但是作为一个前端，我希望自己设计页面，然后使用hexo的后端实现。但是我现在不太清楚该如何修改这个博客的样式并且不影响到他后端的一些实现，求指点下方向0.0

**Comment by levonlin** [comment]
首先得给你澄清一点，hexo只是是用来生成静态博客的、和后端没有关系，也就是说你把markdown格式的文章写好后由hexo只是负责渲染为html，然后它所谓的发布只是利用git的把你的生成好的博客push到任何可以提供静态博客服务的托管平台，但其实你把渲染好的html放到任何提供web服务的服务器都可以访问的。。。
所以一般用hexo写博客，只是做了三件事：你写文章、本地hexo渲染、提交页面到托管平台，并不用像wordpress一样担心后端的问题呀~后端是托管平台的事情（当然你自建服务器，而且还想在服务端生成页面除外，如果你想这么做，就参看hexo的文档把，应该有相应的api给后端调用的）。

好了，回到正题，如何写主题就三个字嘛：[看文档](https://hexo.io/zh-cn/docs/themes.html):joy:；其实很简单的~

**Comment by QAQMiao** [comment]
看了两遍之后，好像看懂了0.0。非常非常感谢，刚刚接触这些，很多概念都不是很懂，就想着自己建个博客锻炼下，然后按着教程搭完想改样式的时候就一脸懵逼了。。谢谢前辈，我去看文档了QAQ

**Comment by levonlin** [comment]
其实本人也是学生狗一只，业余瞎捣鼓一下而已，我以前修(shan)改(zai)这个主题也踩了不少坑呢，你一上来就想自己写，很不错哦~

**Comment by QAQMiao** [comment]
也是学生啊[楞]。。大神，可不可以加个好友[膜拜]。。

**Comment by levonlin** [comment]
额，扣扣---1518851268
