### ISSUE TITLE
请教一下，搜索框的高度怎么调整

### ISSUE THREAD

**Issue by wangkunlin** [levonlin/Tinnypp#3]
有点小强迫症，搜索框的高度和前面的文字不一样高。看着别扭。我是新手对前段东西不了解。

**Comment by levonlin** [comment]
用浏览器找到搜索框的css，再去主题里找这段css所在的文件（我看了下，应该是`/source/css/_partial/header.styl`），在搜索框（类名`.search`）下加上`font-size=0`即可。

**Comment by wangkunlin** [comment]
好的，还有个问题就是为何右边的头像不显示呢。我配置文件没修改正确么？

**Comment by levonlin** [comment]
在_config.yml里配置`author_img`字段就可以了

**Comment by wangkunlin** [comment]
我设置了，但是没显示，后来我发现在layout里的一个配置文件中没有代码。头像的div是空的。我自己加上了。

**Comment by levonlin** [comment]
嗯，解决了就好XD
