### ISSUE TITLE
使用搜索功能后，footer和header都错位，您能否修改?

### ISSUE THREAD

**Issue by ipingguo** [levonlin/Tinnypp#6]
1.搜索后，footer左边空白。
2.搜索后，页面底部出现滚动条，可向右拉，此时，header右边出现空白。

个人觉得，搜索后的页面和主页的布局保持一致就好，不知道您是怎么处理的。

**Comment by levonlin** [comment]
搜索页面的样式没调好:sweat:。我已经修复了，你可以更新看看~

**Comment by ipingguo** [comment]
好了
