### ISSUE TITLE
统计功能

### ISSUE THREAD

**Issue by a330202207** [levonlin/Tinnypp#7]
喜欢博主这种博客风格，希望博主能添加**网站访问量**跟**文章浏览量**功能，阿里嘎多

**Comment by levonlin** [comment]
亲，这个只是一个静态博客主题，用于给hexo生成页面、再推到github上让你访问而已。
因为页面是本地生成的所以一开始是拿不到访问数据的，而且貌似托管平台如github也没有提供获取访问量的api；所以目前你只有使用自己的服务器才能用服务端代码获取，要么使用某些站长工具来监控你的域名获取访问信息，主题里的前端代码是无能为力的:disappointed_relieved:

**Comment by a330202207** [comment]
因为我看到NexT这个主题有这个功能还有一些其他的比如腾讯公益404这些功能都是可以设置的，奈何前端太渣啊
具体链接：http://theme-next.iissnan.com/third-party-services.html

**Comment by levonlin** [comment]
next实现时调用了第三方接口来统计
tinnypp可以配置google 的统计。。这是从原来的tinny主题继承来的，但这个主题的作者已经停止维护了，所以也不知道这个配置现在还能不能用
